In [1]:
import pandas as pd
import numpy as np

store = pd.HDFStore('/Users/jiaqizhang/Documents/innovation_day/stock/data/base_store.h5')
base = store['base']

In [2]:
base.columns

Index([u'code', u'close', u'turn', u'mkt_cap', u'open', u'vol', u'adjfactor',
       u'amount', u'swing', u'high', u'low', u'transaction_date', u'ipo_date',
       u'weekday', u'out_date', u'close_7d', u'open_7d', u'closed_diff',
       u'issue_date', u'opprofit', u'non_oper_rev', u'non_oper_exp',
       u'tot_profit', u'tax', u'net_profit_is', u'minority_int_inc',
       u'np_belongto_parcomsh', u'net_cash_flows_oper_act',
       u'stot_cash_outflows_oper_act', u'stot_cash_outflows_inv_act',
       u'net_cash_flows_inv_act', u'stot_cash_outflows_fnc_act',
       u'net_cash_flows_fnc_act', u'monetary_cap', u'tradable_fin_assets',
       u'notes_rcv', u'acct_rcv', u'oth_rcv', u'prepay', u'dvd_rcv',
       u'int_rcv', u'inventories', u'tot_cur_assets',
       u'fin_assets_avail_for_sale', u'held_to_mty_invest',
       u'invest_real_estate', u'long_term_eqy_invest', u'long_term_rec',
       u'fix_assets', u'intang_assets', u'r_and_d_costs', u'goodwill',
       u'long_term_deferred_exp', u'deferred_tax_assets',
       u'tot_non_cur_assets', u'tot_assets', u'st_borrow', u'notes_payable',
       u'acct_payable', u'adv_from_cust', u'empl_ben_payable',
       u'taxes_surcharges_payable', u'tot_acct_payable', u'int_payable',
       u'dvd_payable', u'oth_payable', u'tot_cur_liab', u'lt_borrow',
       u'bonds_payable', u'tot_liab', u'eqy_belongto_parcomsh', u'cap_rsrv',
       u'surplus_rsrv', u'undistributed_profit',
       u'other_equity_instruments_PRE', u'tot_liab_shrhldr_eqy',
       u'days_since_ipo'],
      dtype='object')

In [3]:
keep_vars = ['code', 'close', 'transaction_date']
rnn_base = base[keep_vars]

In [4]:
rnn_base

              code   close transaction_date
0        000001.sz    5.49       2011-01-04
1        000001.sz    5.46       2011-01-05
2        000001.sz    5.42       2011-01-06
3        000001.sz    5.62       2011-01-07
4        000001.sz    5.48       2011-01-10
5        000001.sz    5.55       2011-01-11
6        000001.sz    5.62       2011-01-12
7        000001.sz    5.60       2011-01-13
8        000001.sz    5.48       2011-01-14
9        000001.sz    5.27       2011-01-17
10       000001.sz    5.26       2011-01-18
11       000001.sz    5.31       2011-01-19
12       000001.sz    5.11       2011-01-20
13       000001.sz    5.19       2011-01-21
14       000001.sz    5.16       2011-01-24
15       000001.sz    5.20       2011-01-25
16       000001.sz    5.23       2011-01-26
17       000001.sz    5.25       2011-01-27
18       000001.sz    5.21       2011-01-28
19       000001.sz    5.25       2011-01-31
20       000001.sz    5.29       2011-02-01
21       000001.sz    5.23       2011-02-09
22       000001.sz    5.30       2011-02-10
23       000001.sz    5.31       2011-02-11
24       000001.sz    5.48       2011-02-14
25       000001.sz    5.42       2011-02-15
26       000001.sz    5.44       2011-02-16
27       000001.sz    5.48       2011-02-17
28       000001.sz    5.48       2011-02-18
29       000001.sz    5.47       2011-02-21
...            ...     ...              ...
4233395  603986.sh  177.97       2016-09-26
4233396  603986.sh  177.97       2016-09-27
4233397  603986.sh  177.97       2016-09-28
4233398  603986.sh  177.97       2016-09-29
4233399  603986.sh  177.97       2016-09-30
4233400  603986.sh  177.97       2016-10-10
4233401  603986.sh  177.97       2016-10-11
4233402  603986.sh  177.97       2016-10-12
4233403  603986.sh  177.97       2016-10-13
4233404  603986.sh  177.97       2016-10-14
4233405  603986.sh  177.97       2016-10-17
4233406  603986.sh  177.97       2016-10-18
4233407  603986.sh  177.97       2016-10-19
4233408  603986.sh  177.97       2016-10-20
4233409  603986.sh  177.97       2016-10-21
4233410  603986.sh  177.97       2016-10-24
4233411  603986.sh  177.97       2016-10-25
4233412  603986.sh  177.97       2016-10-26
4233413  603986.sh  177.97       2016-10-27
4233414  603986.sh  177.97       2016-10-28
4233415  603986.sh  177.97       2016-10-31
4233416  603986.sh  177.97       2016-11-01
4233417  603986.sh  177.97       2016-11-02
4233418  603986.sh  177.97       2016-11-03
4233419  603986.sh  177.97       2016-11-04
4233420  603986.sh  177.97       2016-11-07
4233421  603986.sh  177.97       2016-11-08
4233422  603986.sh  177.97       2016-11-09
4233423  603986.sh  177.97       2016-11-10
4233424  603986.sh  177.97       2016-11-11

[4233425 rows x 3 columns]